### ISSUE TITLE
Add support for new I2C IR sensor devboards

### ISSUE THREAD

**Issue by aninternetof** [rovercode/rovercode#126]
The sensor is the VCNL4010.

Each sensor is wired to its own I2C bus, just in case we can't toggle their addresses. See here: https://upverter.com/ductape/084de978df61d3cb/rovercode/

Here's a good startup sequence: https://github.com/ControlEverythingCommunity/VCNL4010/blob/master/Python/VCNL4010.py

**Comment by cabarnes** [comment]
Fixed by #134
