### ISSUE TITLE
Make rover start on boot when on rover hardware

### ISSUE THREAD

**Issue by aninternetof** [rovercode/rovercode#78]
But not on development hardware

**Comment by ryanknutson** [comment]
Would adding the script to /etc/rc.local work? If not, a cron job would work well.

**Comment by aninternetof** [comment]
Either would work great! I think I prefer the cron job.

I wonder if we can add something to setup.sh to create the cron job during install.

**Comment by ryanknutson** [comment]
This command adds the script to /etc/rc.local
`sed -e '$i \sh /install/dir/start.sh \n' /etc/rc.local`

**Comment by aninternetof** [comment]
I like this plan. Do things started through rc.local run with root privileges? start.sh will need them.

**Comment by ryanknutson** [comment]
Yes, it runs as root.

**Comment by aninternetof** [comment]
Next decision: how should we make setup.sh do this local.rc addition when installing on the target hardware (CHIP, RaspPi, BeagleBone), but not when installing on a development PC? 

We could have it try to read the cpu procinfo and figure out on its own what kind of system it is on. 

Or, we could just have the user pass a flag into setup.sh. That would probably be simpler, and less risk of it getting it wrong.

**Comment by cabarnes** [comment]
You could have `setup.sh` ask the user rather than needing them to supply a parameter.

**Comment by aninternetof** [comment]
I like that.

**Comment by ryanknutson** [comment]
It should ask the user, that way a developer that isn't paying attention doesn't risk messing up their rc.local

**Comment by ryanknutson** [comment]
I think I have it working. See f54d4eab3dcd0a6fdb5e8d452f1f15ccbbfd1ddb.

**Comment by aninternetof** [comment]
LGTM. Want to make a pull request for it?

**Comment by cabarnes** [comment]
Merged
